# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'BaseProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BaseProject

  pod 'Masonry' , '~> 1.1.0'
  
  pod 'AFNetworking', '~> 3.1.0'
  pod 'SDWebImage' , '~>3.8'
  pod 'MJExtension'
  pod 'MBProgressHUD' , '~> 1.1.0'
  
  pod 'MJRefresh'
  
  pod 'FDFullscreenPopGesture'
  pod 'IQKeyboardManager', '~> 6.0.3'
  

end
